server:
  address: 0.0.0.0
  port: 8080
spring:
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        globally_quoted_identifiers: true
        format_sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
jwt:
  lifetime: 5m
  secret: ${JWT_SECRET}
admin:
  login: ${ADMIN_LOGIN}
  email: ${ADMIN_EMAIL}
  password: ${ADMIN_PASSWORD}

logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE