server:
  address: 0.0.0.0
  port: 8080

spring:
  jpa:
    database: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
jwt:
  lifetime: 5m
  secret: ${JWT_SECRET}